SELECT A.ID, A.NAME, A.HOST_ID 
FROM PLACES AS A JOIN 
(SELECT HOST_ID, COUNT(HOST_ID) AS COUNT
FROM PLACES
GROUP BY HOST_ID
) AS B ON A.HOST_ID = B.HOST_ID
WHERE B.COUNT>=2
ORDER BY A.ID;

SELECT  * 
FROM PLACES
WHERE HOST_ID IN
(SELECT HOST_ID
FROM PLACES
GROUP BY HOST_ID
HAVING COUNT(HOST_ID) >= 2)
ORDER BY ID;