SELECT ANIMAL_ID, ANIMAL_TYPE, NAME
FROM ANIMAL_OUTS
WHERE SEX_UPON_OUTCOME NOT LIKE '%Intact%'
    AND ANIMAL_ID IN 
    (SELECT ANIMAL_ID
    FROM ANIMAL_INS
    WHERE SEX_UPON_INTAKE LIKE '%Intact%')
ORDER BY ANIMAL_ID;

SELECT O.ANIMAL_ID, O.ANIMAL_TYPE, O.NAME
FROM ANIMAL_OUTS AS O JOIN ANIMAL_INS AS I ON O.ANIMAL_ID = I.ANIMAL_ID
WHERE O.SEX_UPON_OUTCOME NOT LIKE '%Intact%'
AND I.SEX_UPON_INTAKE LIKE '%Intact%'
ORDER BY O.ANIMAL_ID;