SELECT ANIMAL_ID, NAME, SUBSTRING(DATETIME,1,10) AS '날짜'
FROM ANIMAL_INS
ORDER BY ANIMAL_ID;

-- DATE_FORMAT
SELECT ANIMAL_ID, NAME, DATE_FORMAT(DATETIME,'%Y-%m-%d') AS '날짜'
FROM ANIMAL_INS
ORDER BY ANIMAL_ID;