SELECT ANIMAL_ID, NAME, 
CASE 
WHEN SEX_UPON_INTAKE LIKE '%Intact%' THEN 'X'
ELSE 'O' 
END AS '중성화'
FROM ANIMAL_INS
ORDER BY ANIMAL_ID;

SELECT ANIMAL_ID, NAME, 
CASE SEX_UPON_INTAKE 
WHEN 'Intact Male' THEN 'X' 
WHEN 'Intact Female' THEN 'X' 
ELSE 'O' END
FROM ANIMAL_INS;